### ISSUE TITLE
Either switch SASLAuth() method list to unicode or reject unicode args

### ISSUE THREAD

**Issue by JocelynDelalande** [icgood/pysasl#1]
- `SASLAuth([b'PLAIN'])` will work and populate the  `server_mechanism` attribute.
- `SASLAuth(['PLAIN'])` will fail silently and do not populate the  `server_mechanism` attribute.

I understand historical (py2) reason but I don't see any reason of using a bytes rather than unicode parameter here. I suggest:
- switching to unicode and still accepting bytes (decoding it to unicode on the fly)
- optionally issuing a DepredactionWarning

If you do not want to change that arg type, then I would expect a type assertion to avoid failing silently with something that may seem valid.

PS: yay, issue #1 ! :fireworks:

**Comment by icgood** [comment]
I don't believe this issue is still relevant after #9, which includes some discussion.
